name: Random Joke
author: Shreyansh Pandey
description: Fetch a random joke from the JokeAPI and post it to Slack

inputs:
  slack_username:
    description: Slack username to post the joke
    required: false
  upload_joke:
    description: Upload the joke as an artifact
    required: false
    default: false
  slack_webhook:
    description: Slack webhook URL to post the joke
    required: false

outputs:
  joke:
    description: The random joke fetched from the JokeAPI
    value: ${{ steps.fetch-joke.outputs.random_joke }}

runs:
  using: composite
  steps:
    - name: Fetch random joke
      id: fetch-joke
      shell: bash
      run: |
        joke=$(curl -s https://icanhazdadjoke.com/ -H "Accept: text/plain")
        echo "random_joke=${joke}" >> $GITHUB_OUTPUT
        
    - name: Create joke file
      if: ${{ inputs.upload_joke == 'true' }}
      shell: bash
      run: echo "${{ steps.fetch-joke.outputs.random_joke }}" > joke.txt
      
    - name: Upload joke artifact
      if: ${{ inputs.upload_joke == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: random-joke
        path: joke.txt
        
    - name: Send Slack message
      if: ${{ inputs.slack_webhook != '' }}
      uses: docker://technosophos/slack-notify
      env:
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
        SLACK_TITLE: " Random Joke Time!"
        SLACK_MESSAGE: ${{ inputs.slack_username && format('@{0}: {1}', inputs.slack_username, steps.fetch-joke.outputs.random_joke) || steps.fetch-joke.outputs.random_joke }}
        SLACK_COLOR: "#723fc4"