name: Random Joke
author: Shreyansh Pandey
description: Fetch a random joke from the JokeAPI and post it to Slack

inputs:
  slack_username:
    description: Slack username to post the joke
    required: false
  upload_joke:
    description: Upload the joke as an artifact
    required: false
    default: false
  slack_webhook:
    description: Slack webhook URL to post the joke
    required: false

outputs:
  joke:
    description: The random joke fetched from the JokeAPI
    value: ${{ steps.fetch-joke.outputs.random_joke }}

runs:
  using: composite
  steps:
    - name: Fetch random joke
      id: fetch-joke
      shell: bash
      run: |
        joke=$(curl -s https://icanhazdadjoke.com/ -H "Accept: text/plain")
        echo "random_joke=${joke}" >> $GITHUB_OUTPUT
        
    - name: Create joke file
      if: ${{ inputs.upload_joke == 'true' }}
      shell: bash
      run: echo "${{ steps.fetch-joke.outputs.random_joke }}" > joke.txt
      
    - name: Upload joke artifact
      if: ${{ inputs.upload_joke == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: random-joke
        path: joke.txt