name: Artifacts
on: [push]

jobs:
    Upload-an-artifact:
        runs-on: ubuntu-latest
        name: Upload name.txt
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: My-Name
                path: home/shreyansh.pandey@simform.dom/actions-1/name.txt

            - name: List-all-Files
              run: |
                echo "Files in this directory are: "
                ls -la
                echo "Files Uploaded"
             