name: Concurrency-1
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: "Select an environment"
                type: environment
                required: true
            
jobs:
    sleep:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep for 30 seconds
              run: sleep 30