name: Pull Request Comment
on:
    pull_request:
        types: [opened]
 
jobs:
    pr-comment:
        runs-on: ubuntu-latest
        steps:
           - name: Comment for new PRs
             uses: actions/github-script@v6 #Javascript in your steps access to github rest api provided
             with:
              script: |
                github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: 'Thanks for Contributing',
                });