name: Simple-Action
on: [push]

jobs: 
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS action
              id: greet
              uses: actions/hello-world-javascript-action@main #@v1.2.0 or @v1 or @commit_id
              with:
                who-to-greet: Shreyansh
                
            - name: Log Greet Time
              run: echo "{{ steps.greet.ouputs.time }}""