name : Stale Issues and PRs

on:
    schedule:
        - cron: "43 11 * * *" 

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/stale@v8
            with:
              stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs.'  
              days-before-stale: 1
              days-before-close: 5
             