name: Status Check Functions
on: [push]

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Step1
              run: sleep 20
              timeout-minutes: 1

            - name: Step2
              id: step-2
              continue-on-error: true
              run: exit 1

            - name: Runs on failure
              if: failure() && steps.step-2.conclusion == 'failure'
              #run: echo 'Runs on failure'
              run: "Step2 has failed"

              #Below not needed as it's the default behavior
            - name: Runs on success
              if: success()
              run: echo 'Runs on success'

            - name: Always runs
              if: always()
              run: echo 'Always runs'

            - name: Runs when cancelled
              if: cancelled()
              run: echo 'Runs when workflow cancelled'
              
    job-2:
        runs-on: ubuntu-latest
        needs: job-1
        if : failure()
        steps:
            - name: Step2
              run: echo 'This job runs only if job-1 fails'