#You can have nested workflows
#1 calls 2 , 2 calls 3
#But you are restricted to only 4 levels of nesting including caller

name: Calling Reusable Workflow 
on: 
    workflow_dispatch:
        inputs:
            name:
                description: 'Name'
                type: string
                default: "Shreyansh"
                required: false

jobs:
    calling-reusable-workflow:
        uses: CICD-019/workflows/.github/workflows/reusable.yml@main 
        with:
            name: '${{ inputs.name}}'
        secrets: #inherit - pass all secrets from here to called workflow
            access-token: ${{ secrets.ACCESS_TOKEN }}

    calling-reusable-workflow-from-same-repo:
        uses: ./.github/workflows/reusable-workflow.yaml
    
    using-reusable-workflow-output:
        runs-on: ubuntu-latest
        needs: calling-reusable-workflow-from-same-repo
        steps:
            - run: echo ${{ needs.calling-reusable-workflow-from-same-repo.outputs.date }}
            