name: VARIABLES AND SECRETS
on: [push]

jobs:
    log-vars:
        runs-on: ${{ vars.JOBS_RUNNER }}
        env:
            BOOLEAN_SECRET: ${{ secrets.my_secret }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
            ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
        steps:
                -  name: Runs only if secret is true
                   if: env.BOOLEAN_SECRET == 'true'
                   run: echo "Secret is true, running this step"
                -  name: Log Vars
                   run: |
                      echo '${{ vars.JOBS_RUNNER }}'
                      echo '${{ vars.ENV_LEVEL_VAR }}'
                      echo '${{ vars.REPO_LEVEL_VAR }}'
                      echo '${{ vars.ORG_LEVEL_VAR }}'  
