name: Working Dir and Shells
on: [push]
defaults:
    run:
        shell: bash
        # working-directory: D:/github as long as this dir exists you can override
jobs:
  display-working-dir-and-list-files-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Display Working Directory and List Files
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_WORKSPACE
        echo $GITHUB_REPOSITORY
    - name: Change work dir for one step
      working-directory: /home/runner
      run: pwd


  display-working-dir-and-list-files-windows:
    runs-on: windows-latest
    defaults:
        run:
            shell: pwsh
    steps:
        - name: Display Working Directory and List Files
          run: |
                pwd
                ls 
                echo $env:GITHUB_SHA
                echo $env:GITHUB_WORKSPACE
                echo $env:GITHUB_REPOSITORY
        - name: Python Shell override
          run: |
                import platform
                print(platform.processor())
          shell: python